---
title: "Operating Unit Level (OU Level)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.path = "../Figs/")
```

```{r init, warning= FALSE, message=FALSE}
library(kableExtra)
library(xtable)

```

## Overall Achievement (OU Level)

This table shows orverall achievement of the country from FY15 to FY17

```{r ou_level,warning= FALSE, message=FALSE}

knitr::kable(ou_level,"html") %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                  full_width = F, position = "float_right",font_size = 12)

```


## Overall Indicator achievement

```{r ,warning= FALSE, message=FALSE}

print(g_ou_level)

```



## Cascade FY17

```{r ,warning= FALSE, message=FALSE}

print(gg_cascade)

```



## TX_NEW Trend

```{r ,warning= FALSE, message=FALSE}

print(tx_new_trend)

```



## TX_CURR Trend

```{r ,warning= FALSE, message=FALSE}

print(tx_curr_trend)

```



## HTS and PMTCT_STAT yield

```{r ,warning= FALSE, message=FALSE}

print(gg_hts_yield)

```




## Linkage to Treatment

```{r ,warning= FALSE, message=FALSE}

print(gg_linkage)

```


